//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Interface")]
    public interface Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/test", ReplyAction="http://tempuri.org/Interface/testResponse")]
        string test(string g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/test", ReplyAction="http://tempuri.org/Interface/testResponse")]
        System.Threading.Tasks.Task<string> testAsync(string g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/CheckLogin", ReplyAction="http://tempuri.org/Interface/CheckLoginResponse")]
        int CheckLogin(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/CheckLogin", ReplyAction="http://tempuri.org/Interface/CheckLoginResponse")]
        System.Threading.Tasks.Task<int> CheckLoginAsync(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddLogin", ReplyAction="http://tempuri.org/Interface/AddLoginResponse")]
        int AddLogin(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/AddLogin", ReplyAction="http://tempuri.org/Interface/AddLoginResponse")]
        System.Threading.Tasks.Task<int> AddLoginAsync(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/ErrorDescription", ReplyAction="http://tempuri.org/Interface/ErrorDescriptionResponse")]
        string ErrorDescription(int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface/ErrorDescription", ReplyAction="http://tempuri.org/Interface/ErrorDescriptionResponse")]
        System.Threading.Tasks.Task<string> ErrorDescriptionAsync(int k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceChannel : ConsoleApplication3.ServiceReference1.Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceClient : System.ServiceModel.ClientBase<ConsoleApplication3.ServiceReference1.Interface>, ConsoleApplication3.ServiceReference1.Interface {
        
        public InterfaceClient() {
        }
        
        public InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string test(string g) {
            return base.Channel.test(g);
        }
        
        public System.Threading.Tasks.Task<string> testAsync(string g) {
            return base.Channel.testAsync(g);
        }
        
        public int CheckLogin(string login, string pass) {
            return base.Channel.CheckLogin(login, pass);
        }
        
        public System.Threading.Tasks.Task<int> CheckLoginAsync(string login, string pass) {
            return base.Channel.CheckLoginAsync(login, pass);
        }
        
        public int AddLogin(string login, string pass) {
            return base.Channel.AddLogin(login, pass);
        }
        
        public System.Threading.Tasks.Task<int> AddLoginAsync(string login, string pass) {
            return base.Channel.AddLoginAsync(login, pass);
        }
        
        public string ErrorDescription(int k) {
            return base.Channel.ErrorDescription(k);
        }
        
        public System.Threading.Tasks.Task<string> ErrorDescriptionAsync(int k) {
            return base.Channel.ErrorDescriptionAsync(k);
        }
    }
}
